### PR TITLE
Feature/summit generator

### PR DESCRIPTION
**Pull request by unclecheese**
Adds a "dev tools" button to the Summit admin allowing some basic tasks that assist when in dev mode:

* **Force phase**: will automatically set all the date ranges to force a specific phase of the summit (voting, selection, registration, etc)
* **Reset votes**: Deletes all the votes in the summit (todo: Randomly assign votes?)
* **Set as active**: Sets this summit as active, and all others as inactive.

### CODE REVIEW

**Comment by smarcet** [comment]
couple of notes
* files keys.dev.pub, and  keys.tags.pub need to be removed from commit ( are generated by vagrant)
* re:forcephase feature i think that should have in consideration the summit time zone ( i could be wrong) bc we are storing UTC datetime on those fields
regards

**Comment by jimmytipit** [comment]
For testing purposes, it might be nice to overwrite the local timezone. Aaron is testing from Australia. Or at least note the GMT local time somewhere.

**Comment by unclecheese** [comment]
@smarcet Because I'm using the `setXXXStartDate()` accessors, the dates should be adjusted for timezone, correct?

I've rebased against master.

**Comment by smarcet** [comment]
yes that is correct merging this :)
regards

**Pull request merged**
