### PR TITLE
New Webpack workflow

### PR DESCRIPTION
**Pull request by unclecheese**
## What is this, and why?

Until now, Webpack has been used in different ways across the site. There is a single, monolithic `webpack.config.js` in the web root that serves multiple entry points across multiple modules. Further, there are three modules (video, trackchairs, and voting) that have their own webpack configuration and workflow. As the UX team becomes more reliant on Webpack as a primary tool, it behooves us to remove this fragmentation and establish a scalable and homogenous way of using webpack across the site.

This changeset deprecates the single, monolithic `webpack.config.js` file in the root in favour of per-module configuration and compiling.
## How to use it

There are four tasks that have been added to the `package.json` at the root level of the site that execute scripts in the new `webpack/` folder. These are:
- `build`: Create a production build of the module
- `watch`: Use in dev mode to compile a module as files change
- `serve`: Instantiate a Webpack Dev Server for a module (allows hot loading of modules and React components)
- `build-all`: Run `build` across all modules (used on deployment)
## Example usage

With the exception of `build-all`, all of these scripts require a module name as an argument. 

_build the software/ module_

```
$ npm run build software
```

_watch the summit/ module_

```
$ npm run watch summit
```

_do dev work on the trackchairs module_

```
$ npm run serve summit-trackchair-app
```

_create production builds of every module that uses Webpack_

```
$ npm run build-all
```
## The base config

The base config file provides loaders and plugins that are believed to be common across multiple modules. It provides React, Riot, LESS, and SASS compiling, and more, in addition to other common boilerplate functionality like auto-prefixing. As of now, there are no cases where modules need to add anything special to the base config.
## Per-module configuration

Because needs vary so strongly across the site, each module is empowered to deviate from the standard Webpack configuration, and inject its own concerns. Rather than adding every entry point across the entire site to a single `webpack.config.js` file, each module provides its entry and output points, relative to its directory.

_software/webpack.config.js_

``` js
module.exports = {
  entry: {
    "js/public/software_all_projects": "./js/software_all_projects.js",
    "js/public/software_sample_configs":"./js/software_sample_configs.js",
  },

  output: {
    path: __dirname ,
    filename: "[name].bundle.js"
  }
};
```

Further, dynamic configurations can be made by defining the config file as a function.

``` js
module.exports = (baseConfig) => {
  const myConfig = {...baseConfig}; 
  if(baseConfig.plugins.length) {
       // do something
   }

   return myConfig;
}
```
## Infrastructure changes

Instead of running `./webpack` on deployment, we'll need to run `npm run build-all`.
## Other changes included in this pull request
- Removal of deprecated modules (e.g. new-trackchairs-app)
- Update of npm packages, as defined by their version constraints (minor releases only)
- Regeneration of bundle files
- Update to READMEs of affected modules

### CODE REVIEW

**Comment by smarcet** [comment]
Aaron, i noticed that u updated the version of riot from  "riot": "2.3.13", to latest one
that would break the summit module, from the time being and considering that we are on summit time, i will leave this pull request merge until after BCN summit and investigate why latest riotjs version breaks the summit module

regards

**Comment by unclecheese** [comment]
Thanks, Sebastian. Good catch. Riot does not need to be upgraded. I've set all the riot packages back to their original versions.

Other than that, if the workflow looks okay to you, can we get this on dev, and hold on a production merge until post summit?

**Comment by smarcet** [comment]
OK i agree, i will merge this and update deployment procedure on dev

regards

**Comment by unclecheese** [comment]
Hi, Sebastian,

Have made several updates to this PR. Don't let the number of files changed scare you. Most of those are just moves. In addition to everything above, these new changes enforce a directory structure on each module that uses webpack builds. Each module must contain a `ui/` directory that contains a `webpack.config.js`, a `package.json` (if needed), and `source/` and `production/` subfolders. Example:

* summit/
  * ui/
    * production/
    * source/
      *js/
    * webpack.config.js
    * package.json

This enforces a convention on the way webpack is used across the site, and affords us new template shortcuts, `$ModuleJS` and `$ModuleCSS`. Example:

`$ModuleJS('summit-highlights')` loads `summit/ui/production/js/summit-highlights.js` for all controllers in the summit module.

Nothing else has changed. For deployments, you will need to use the new script `npm run build-all` instead of `webpack` to generate all of the bundles.

As stated in our last dev meeting, these changes are a necessary stepping stone to opening up a lot of doors to improve the workflow of the UX team.

**Comment by smarcet** [comment]
Ok sure will take a look tomorrow first thing in morning cheers

**Comment by smarcet** [comment]
so i have some questions. where the bundles will be generated ? on the production/ui folders? will be the .bundle ext will be maintained ? 
these changes are needed on the summit schedule app as well? or we could maintain its current structure ?

regards

**Comment by smarcet** [comment]
i applied the patch, clean all the .bundle files ( those are not uploaded to git, bc they are generated on fly) run the build, and the schedule app got broken, the files are not generated anymore, you could check that we have plenty of template that use these bundle files on template like

summit/templates/Layout/SummitAppSchedPage.ss

i managed to fix that locally using your $ModuleJS('schedule') but i am not quite sure to uploaded the transpiled sources to  git, bc they are generated automatically

so i would 2 things,

1)we need to fix the broken parts of the site that still using the .bundle files
2) we need to remove from git the transpiled files bc they are generated by npm run build-all

**Comment by unclecheese** [comment]
Thanks, Sebastian. Looks like I missed a couple `.bundle.js` references. I've cleaned those up.  Have also added a rule to ignore `*/ui/production`.

**Comment by smarcet** [comment]
i am getting following error when i do the webpack build

/***************** 
 * Building summit-voting-app
\*****************

[webpack:build] Hash: 9ccfe684239e30e52368
Version: webpack 1.13.3
Time: 2320ms
       Asset       Size  Chunks             Chunk Names
  js/main.js  460 bytes       0  [emitted]  main
css/main.css  467 bytes       0  [emitted]  main

ERROR in ./summit-voting-app/ui/source/js/init.js
Module build failed: TypeError: [BABEL] /home/smarcet/git/openstack-org/summit-voting-app/ui/source/js/init.js: Invalid options type for foreign
    at Logger.error (/home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:211:16)
    at /home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:14
    at /home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:316:22
    at Array.map (native)
    at OptionManager.resolvePresets (/home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (/home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/home/smarcet/git/openstack-org/summit-voting-app/node_modules/babel-core/lib/transformation/file/index.js:223:65)
 @ ./summit-voting-app/ui/source/index.js 5:0-20
Child extract-text-webpack-plugin:


tried to debug but no dice

i already installed all the dependencies running
npm install first


but our schedule app still broken
seems that several files were moved to another place
checking to fix it
regards

**Comment by unclecheese** [comment]
@smarcet I think it's a version compatibility issue with Babel. Can you try removing the `node_modules` directory at the root, and reinstall all the dependencies?

**Pull request merged**
