### PR TITLE
[User Survey] Updates Japanese translation

### PR DESCRIPTION
**Pull request by amotoki**
BTW, jp_JP is the correct local name? ja_JP (or ja) is usual.

### CODE REVIEW

**Comment by smarcet** [comment]
Yes it's correct is due to gettext liberal on php regards

**Comment by smarcet** [comment]
sorry i revisited the documentation and you are rite

lang should be ja_JP i will fix it

regards

**Comment by smarcet** [comment]
ok done, also re enabled Japanese on lang selector
https://github.com/OpenStackweb/openstack-org/commit/16aa01957d00a4371cad4545beb5439b85dac75f

ごめん なさい

**Comment by ianychoi** [comment]
Hello @smarcet !

Would you also reflect survey.js file change 16aa01957d00a4371cad4545beb5439b85dac75f to production branch?
It seems that survey.js needs to be published to survey_builder/ui/production/js/survey.js

**Comment by smarcet** [comment]
sure no problem we will deploy today
regards

**Comment by smarcet** [comment]
this is done

regards

**Pull request merged**
